### ISSUE TITLE
constant 4278190080 overflows int - will not compile on 32-bit?

### ISSUE THREAD

**Issue by rabbitear** [NullHypothesis/sybilhunter#7] opened 2016-05-03 22:57 UTC
Running:

```
$ go get github.com/NullHypothesis/sybilhunter
```

Returns this to the console:

```
# github.com/NullHypothesis/sybilhunter
../../NullHypothesis/sybilhunter/uptime.go:90: constant 4278190080 overflows int
```

Program will not compile, on a 32-bit machine with 3MB of ram.

**Comment by NullHypothesis** [comment] 2016-05-05 18:50
Thanks for reporting this! I could reproduce the issue. I pushed a patch to the branch `32-bit-compilation`. It works for me when compiling with GOARCH=386. Do you want to give it a shot before I merge it to master?

**Comment by rabbitear** [comment] 2016-05-20 19:44
On Thu, May 05, 2016 at 11:50:02AM -0700, Philipp Winter wrote:

> Thanks for reporting this! I could reproduce the issue. I pushed a patch to the branch `32-bit-compilation`. It works for me when compiling with GOARCH=386. Do you want to give it a shot before I merge it to master?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NullHypothesis/sybilhunter/issues/7#issuecomment-217241063

I got the below output, I'm somewhat new to 'go' itself.  Do I have to
do some 'branch' magic with get to pull the new material ?

Jon.

---snip---
[kreator@calculus][~]% cd $GOPATH/src/github.com 
[kreator@calculus][~/dev/gowork/src/github.com]% rm -rf NullHypothesis 
[kreator@calculus][~/dev/gowork/src/github.com]% echo $GOARCH
386
[kreator@calculus][~/dev/gowork/src/github.com]% go get github.com/NullHypothesis/sybilhunter

# github.com/NullHypothesis/sybilhunter NullHypothesis/sybilhunter/uptime.go:90: constant 4278190080 overflows int

[kreator@calculus][~/dev/gowork/src/github.com]% 
---snip---

## 

(\ /)
( . .)   Jon's website is here:
c(")(")   http://www.securityrabbit.com

**Comment by rabbitear** [comment] 2016-05-20 19:44
On Thu, May 05, 2016 at 11:50:02AM -0700, Philipp Winter wrote:

> Thanks for reporting this! I could reproduce the issue. I pushed a patch to the branch `32-bit-compilation`. It works for me when compiling with GOARCH=386. Do you want to give it a shot before I merge it to master?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NullHypothesis/sybilhunter/issues/7#issuecomment-217241063

I just try this:

$ git cherry-pick ed62bb7

Then ran

$ go install

And it compiled :)

Jon.

## 

(\ /)
( . .)   Jon's website is here:
c(")(")   http://www.securityrabbit.com

**Comment by NullHypothesis** [comment] 2016-05-20 23:24
Thanks, merged to master.

**Closed as completed by NullHypothesis** 2016-05-20 23:24 UTC
